version: "3.3"
services:
  tunnel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_VERSION: 22.04
        AWSCLI_VERSION: 2.11.12
    # Supports linux/amd64 and linux/arm64. Uncomment one of the below lines if you want to use that specific platform.
    # platform: linux/amd64
    # platform: linux/arm64
    container_name: db-tunnel
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      RDS_HOST: ${RDS_HOST}
      INSTANCE_NAME: ${INSTANCE_NAME}
    ports:
      - 5555:5555
    entrypoint: ["/setup-tunnel.sh"]
